title: Temporal Dead Zone
author: Alexander Huang
email: alxdhuang@gmail.com
description: >
  Alexander Huang's blog. On programming, physics, mathematics, and literature
  etc.
  

url: https://alxdhuang.github.io

show_excerpts: true

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: alxdhuang/minima-rock

google_analytics: true

kramdown:
  parse_block_html: true

more_posts: /tags.html
