title: Alexander Huang's Blog
author: Alexander Huang
url: https://alxdhuang.github.io

permalink: /:year/:month/:day/:title.html

collections:
  authors:
    output: false

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag